"""Build the product-field index: which JSON field paths already exist, and where.

Read-only. Scans bridge/*.json and emits 0_core_shared/schema/fields.json.

Why this exists
---------------
The rule is "reuse before invent": before adding a field to a collector, check
whether a field with that meaning already exists somewhere. The engine-interface
side of that rule is already enforced (docs/interface-baseline.json +
build-data-inventory.py --check). The *field* side had no entry point at all --
18400 field paths existed with nothing to look them up in. This is that entry point.

Usage
-----
    python 0_core_shared/build-fields-index.py            # write fields.json
    python 0_core_shared/build-fields-index.py --check    # print summary only
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUT = HERE / "schema" / "fields.json"

DEFAULT_STAGING = Path(
    "C:/Program Files (x86)/Steam/userdata/1070536217/1066780/local/staging_area/tpf2mcp_1"
)
MAX_DEPTH = 7
MAX_ARRAY_SAMPLES = 200
MAX_FILE_MB = 120


def bridge_dir() -> Path | None:
    env = os.environ.get("TPF2_MCP_MOD_DIR")
    if env:
        candidate = Path(env) / "bridge"
        if candidate.is_dir():
            return candidate
    if (DEFAULT_STAGING / "bridge").is_dir():
        return DEFAULT_STAGING / "bridge"
    return None


def type_name(value) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "bool"
    if isinstance(value, int):
        return "int"
    if isinstance(value, float):
        return "number"
    if isinstance(value, str):
        return "string"
    if isinstance(value, list):
        return "array"
    if isinstance(value, dict):
        return "object"
    return "unknown"


def walk(value, prefix: str, out: dict, depth: int) -> None:
    if depth > MAX_DEPTH:
        return
    if isinstance(value, dict):
        for key, item in value.items():
            path = f"{prefix}.{key}" if prefix else str(key)
            entry = out.setdefault(path, {"types": set(), "samples": []})
            entry["types"].add(type_name(item))
            if len(entry["samples"]) < 3 and not isinstance(item, (dict, list)):
                entry["samples"].append(item)
            walk(item, path, out, depth + 1)
    elif isinstance(value, list):
        child_prefix = prefix + "[]"
        for item in value[:MAX_ARRAY_SAMPLES]:
            walk(item, child_prefix, out, depth + 1)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="print summary, do not write")
    args = parser.parse_args()

    bridge = bridge_dir()
    if bridge is None:
        print("[skip] no bridge directory found (set TPF2_MCP_MOD_DIR)")
        return 0

    files = sorted(bridge.glob("*.json"))
    fields: dict[str, dict] = {}
    per_file: dict[str, int] = {}
    skipped: list[str] = []

    for path in files:
        size_mb = path.stat().st_size / (1024 * 1024)
        if size_mb > MAX_FILE_MB:
            skipped.append(f"{path.name} ({size_mb:.0f} MB)")
            continue
        try:
            payload = json.loads(path.read_text(encoding="utf-8", errors="replace"))
        except Exception as err:
            skipped.append(f"{path.name} (parse: {err.__class__.__name__})")
            continue

        local: dict[str, dict] = {}
        walk(payload, "", local, 0)
        per_file[path.name] = len(local)

        for field_path, entry in local.items():
            target = fields.setdefault(field_path, {"types": set(), "in": set(), "samples": []})
            target["types"] |= entry["types"]
            target["in"].add(path.name)
            for sample in entry["samples"]:
                if len(target["samples"]) < 3 and sample not in target["samples"]:
                    target["samples"].append(sample)

    serializable = {
        name: {
            "types": sorted(entry["types"]),
            "in": sorted(entry["in"]),
            "samples": entry["samples"],
        }
        for name, entry in sorted(fields.items())
    }

    document = {
        "_note": "Generated by 0_core_shared/build-fields-index.py -- do not hand-edit.",
        "_how_to_use": (
            "Before adding a field to a collector: look for its path here first. "
            "Reuse the existing path if one matches. If none does, add it and say why "
            "in the collector's header comment."
        ),
        "source": str(bridge),
        "files_scanned": len(per_file),
        "files_skipped": skipped,
        "total_fields": len(serializable),
        "fields": serializable,
    }

    if args.check:
        print(f"bridge: {bridge}")
        print(f"files scanned: {len(per_file)}  skipped: {len(skipped)}")
        print(f"distinct field paths: {len(serializable)}")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(document, indent=1, ensure_ascii=False), encoding="utf-8")
    size_kb = OUT.stat().st_size / 1024
    print(f"[ok] {OUT.relative_to(ROOT)}")
    print(f"     files scanned : {len(per_file)}  skipped: {len(skipped)}")
    print(f"     field paths   : {len(serializable)}")
    print(f"     output size   : {size_kb:.0f} KB")
    if skipped:
        print("     skipped       : " + ", ".join(skipped[:5]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
